1999-12-31 19:29:46 INFO root Start primary API version 1.8.21
1999-12-31 19:29:46 INFO root loading script: main
1999-12-31 19:29:48 INFO root successfully loaded script: main
1999-12-31 19:29:52 ERROR root Failed to run wait callback function: Wait.w
Traceback (most recent call last):
  File "/remotelib_qxi/interface/EthernetClientInterface.py", line 21, in w
    self.__test_ping()
  File "/remotelib_qxi/interface/EthernetClientInterface.py", line 69, in __test_ping
    self._test_ping_timer.Start()
AttributeError: 'Timer' object has no attribute 'Start'
1999-12-31 19:29:52 ERROR root Failed to run wait callback function: Wait.w
Traceback (most recent call last):
  File "/remotelib_qxi/interface/EthernetClientInterface.py", line 21, in w
    self.__test_ping()
  File "/remotelib_qxi/interface/EthernetClientInterface.py", line 69, in __test_ping
    self._test_ping_timer.Start()
AttributeError: 'Timer' object has no attribute 'Start'
1999-12-31 19:29:54 ERROR root Debug Server restarted:Listening
1999-12-31 19:29:58 WARNING root Bezel button info not found for: device 4-0
1999-12-31 19:30:03 INFO root Device 4-0 VTLP sync handling began
1999-12-31 19:30:03 INFO root Device 4-0 VTLP sync handling ended
1999-12-31 19:30:03 INFO root Device 4-0 VTLP sync handling began
1999-12-31 19:30:03 INFO root Device 4-0 VTLP sync handling ended
1999-12-31 19:30:10 INFO root Device 4-0 VTLP sync handling began
1999-12-31 19:30:10 INFO root Device 4-0 VTLP sync handling ended
1999-12-31 19:30:14 WARNING root Bezel button info not found for: device 5-0
1999-12-31 19:30:18 INFO root Device 4-0 VTLP sync handling began
1999-12-31 19:30:18 INFO root Device 4-0 VTLP sync handling ended
1999-12-31 19:30:18 INFO root Device 4-0 VTLP sync handling began
1999-12-31 19:30:18 INFO root Device 4-0 VTLP sync handling ended
1999-12-31 19:30:24 ERROR root Debug Server restarted:Listening
